site_name: Gluu Gateway Docs
site_description: Documenation for Gluu Gateway
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/tree/3.1.3/3.1.3
theme_dir: theme/material
extra:
    version: '3.1.3'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
# - Release Notes: 'release-notes/index.md'
# - Whats new in 3.x: '3.x-intro.md'
# - Whats new in 3.1.x: '3.1.x-intro.md'      
- Administration Guide: 
    - 'Installation' : 'administration/installation.md'
    - 'Admin console' :  'administration/admin-console.md'   
    - 'Credentials storage' : 'administration/credentials-stored.md'
    - 'Custom branding' : 'administration/custom-branding.md'
    - 'FAQ' : 'administration/faq.md'
- User Guide: 'user-guide.md'
- Developer Guide: 'developer-guide.md'
