site_name: Gluu Gateway Docs
site_description: Documentation for Gluu Gateway 3.1.3
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2018, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/tree/3.1.3/3.1.3
theme_dir: theme/material
extra:
    version: '3.1.3'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
# - Release Notes: 'release-notes/index.md'
# - Whats new in 3.x: '3.x-intro.md'
# - Whats new in 3.1.x: '3.1.x-intro.md'      
- 'Installation' : 'installation.md'
- 'Configuration' : 'configuration.md'
- 'Admin console' :  'admin-gui.md'   
- 'FAQ' : 'faq.md'
- Plugins: 
    - 'GUI' : 'plugin/gui.md'
    - 'API' :  'plugin/api.md'  
