# Project Information
site_name: Gluu Gateway 4.2 Docs
site_description: Documentation for Gluu Gateway

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/
edit_uri: edit/4.2/docs/source
repo_name: GluuFederation/docs-gg-prod

# Configuration
extra:
    version: '4.2'
theme:
    name: material
#    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
- codehilite
- pymdownx.snippets

# Navigation Menu
nav:
- 'Versions':
    - '4.2': 'https://gluu.org/docs/gg/4.2'
    - '4.1': 'https://gluu.org/docs/gg/4.1'
    - '4.0': 'https://gluu.org/docs/gg/4.0/'
- ' ': 'https://gluu.org'
- ' ': 'https://gluu.org'
- Home: 'index.md'
- Release Notes: 'release-notes.md'
- Installation Guide:
    - 'Installation' : 'installation.md'
    - 'Kubernetes' : 'kubernetes-installation.md'
    - 'Clustering' : 'clustering.md'
    - 'Databaseless Setup': 'db-less-setup.md'
    - 'Upgrade': 'upgrade.md'
- Admin Guide:
    - 'Overview' :  'admin-guide/getting-started.md'
    - 'Configure Services and Routes': 'admin-guide/services-routes-config.md'
    - 'Enable Plugins': 'admin-guide/enable-plugins.md'
    - 'Consumer Configuration': 'admin-guide/consumer-config.md'
    - 'Advanced Configuration': 'admin-guide/other-ui-config.md'
    - 'Component Settings' : 'configuration.md'
    - 'Logs' : 'logs/index.md'
- Plugins:
    - 'OpenID Connect with UMA PEP' : 'plugin/gluu-openid-connect-uma-pep.md'
    - 'OAuth Authn and PEP' : 'plugin/gluu-oauth-auth-pep.md'
    - 'UMA Authn and PEP' :  'plugin/gluu-uma-auth-pep.md'
    - 'OPA PEP': 'plugin/gluu-opa-pep.md'
    - 'Metrics' :  'plugin/gluu-metrics.md'
    - 'Common Features': 'plugin/common-features.md'
- Tutorials:
    - '› Stepped-up Authentication': 'tutorials/oidc-steppedup-auth-tutorial.md'
    - '› OAuth API protection and OPA PEP security': 'tutorials/oauth-auth-opa-pep-tutorial.md'
    - '› Claim Gathering Authorization': 'tutorials/uma-claim-gathering-tutorial.md'
    - '› OpenID Connect Authentication and OPA PEP Authorization': 'tutorials/oidc-opa-tutorial.md'
    - '› OpenID Connect Authentication and UMA PEP Authorization': 'tutorials/oidc-uma-tutorial.md'
    - '› OAuth Spontaneous Scope security': 'tutorials/oauth-spontaneous-scope-auth-pep-tutorial.md'
    - '› OAuth API protection and Scope security': 'tutorials/oauth-auth-pep-tutorial.md'
    - '› Angular OAuth Role Security': 'tutorials/angular-oauth-role-security.md'
- 'FAQ' : 'faq.md'
