# Project Information
site_name: Gluu Gateway 4.0 Beta Docs
site_description: Documentation for Gluu Gateway

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/
edit_uri: edit/4.0/docs/source
repo_name: GluuFederation/docs-gg-prod

# Configuration
extra:
    version: '4.0 Beta'
theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
- codehilite

# Navigation Menu
nav:
- 'Versions':
    - '4.0 Beta': 'https://gluu.org/docs/gg/4.0/'
    - '1.0': 'https://gluu.org/docs/gg/1.0/'
- ' ': 'https://gluu.org'
- ' ': 'https://gluu.org'
- Home: 'index.md'
- Release Notes: 'release-notes.md'      
- 'Components' : 'components.md'
- 'Installation' : 'installation.md'
- 'Configuration' : 'configuration.md'
- 'Admin console' :  'admin-gui.md'   
- Plugins:
    - 'Gluu OpenID Connect and UMA PEP' : 'plugin/gluu-openid-connect-uma-pep.md'
    - 'Gluu OAuth Auth and OAuth PEP' : 'plugin/gluu-oauth-auth-pep.md'
    - 'Gluu UMA Auth and UMA PEP' :  'plugin/gluu-uma-auth-pep.md'
    - 'Gluu OPA PEP': 'plugin/gluu-opa-pep.md'
    - 'Gluu Metrics' :  'plugin/gluu-metrics.md'
    - 'Common Features': 'plugin/common-features.md'
- 'UMA Tutorial': 'uma-tutorial.md'
- 'Logs' : 'logs/index.md'
- 'FAQ' : 'faq.md'
