# Project Information
site_name: Gluu Gateway 4.0 Docs
site_description: Documentation for Gluu Gateway

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/
edit_uri: edit/4.0/docs/source
repo_name: GluuFederation/docs-gg-prod

# Configuration
extra:
    version: '4.0'
theme:
    name: material
#    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
- codehilite
- pymdownx.snippets

# Navigation Menu
nav:
- 'Versions':
    - '4.0': 'https://gluu.org/docs/gg/4.0/'
    - '1.0': 'https://gluu.org/docs/gg/1.0/'
- ' ': 'https://gluu.org'
- ' ': 'https://gluu.org'
- Home: 'index.md'
- Release Notes: 'release-notes.md' 
- Installation Guide:
    - 'Installation' : 'installation.md'
    - 'Clustering' : 'clustering.md'
- Admin Guide:
    - 'Overview' :  'admin-guide/getting-started.md'
    - 'Configure Services and Routes': 'admin-guide/services-routes-config.md'
    - 'Enable Plugins': 'admin-guide/enable-plugins.md'
    - 'Advanced Configuration': 'admin-guide/other-ui-config.md'
    - 'Component Settings' : 'configuration.md'
    - 'Logs' : 'logs/index.md'
- Plugins:
    - 'OpenID Connect with UMA PEP' : 'plugin/gluu-openid-connect-uma-pep.md'
    - 'OAuth Authn and PEP' : 'plugin/gluu-oauth-auth-pep.md'
    - 'UMA Authn and PEP' :  'plugin/gluu-uma-auth-pep.md'
    - 'OPA PEP': 'plugin/gluu-opa-pep.md'
    - 'Metrics' :  'plugin/gluu-metrics.md'
    - 'Common Features': 'plugin/common-features.md'
- Tutorials:
    - 'Stepped-up Authentication': 'tutorials/oidc-steppedup-auth-tutorial.md'
    - 'OAuth API protection and OPA PEP security': 'tutorials/oauth-auth-opa-pep-tutorial.md'
    - 'Claim Gathering Authorization': 'tutorials/uma-claim-gathering-tutorial.md'
    - 'OpenID Connect Authentication and OPA PEP Authorization': 'tutorials/oidc-opa-tutorial.md'
    - 'OAuth API protection and Scope security': 'tutorials/oauth-auth-pep-tutorial.md'  
- 'FAQ' : 'faq.md'
