# Project Information
site_name: Gluu Gateway 1.0 Docs
site_description: Documentation for Gluu Gateway

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/
edit_uri: edit/1.0/docs/source
repo_name: GluuFederation/docs-gg-prod

# Configuration
extra:
    version: '1.0'
theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
- codehilite

# Navigation Menu
nav:
- 'Versions':
    - '1.0': 'https://gluu.org/docs/gg/1.0/'
    - '4.1': 'https://gluu.org/docs/gg/4.1/'
    - '4.0': 'https://gluu.org/docs/gg/4.0/'    
- ' ': 'https://gluu.org'
- ' ': 'https://gluu.org'
- Home: 'index.md'
- Release Notes: 'release-notes.md'      
- 'Components' : 'components.md'
- 'Installation' : 'installation.md'
- 'Configuration' : 'configuration.md'
- 'Admin console' :  'admin-gui.md'   
- Plugins:
    - 'Gluu OAuth PEP' : 'plugin/gluu-oauth-pep.md'
    - 'Gluu UMA PEP' :  'plugin/gluu-uma-pep.md'
    - 'Gluu Metrics' :  'plugin/gluu-metrics.md'
- 'UMA Tutorial': 'uma-tutorial.md'
- 'Logs' : 'logs/index.md'
- 'FAQ' : 'faq.md'
