site_name: Gluu Gateway Docs
site_description: Documentation for Gluu Gateway 4.0.beta
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2018, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-gg-prod/tree/4.0.beta/docs
theme_dir: theme/material
extra:
    version: '4.0.beta'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
pages:
- Home: 'index.md'
# - Release Notes: 'release-notes/index.md'
# - Whats new in 3.x: '3.x-intro.md'
# - Whats new in 3.1.x: '3.1.x-intro.md'      
- 'Installation' : 'installation.md'
- 'Configuration' : 'configuration.md'
- 'Admin console' :  'admin-gui.md'   
- Plugins:
    - 'Gluu OAuth PEP' : 'plugin/gluu-oauth-pep.md'
    - 'Gluu UMA PEP' :  'plugin/gluu-uma-pep.md'
- Logs : 'logs/index.md'
- 'FAQ' : 'faq.md'
